const sampleTitles = [
  "Starter Plan",
  "Pro Workspace",
  "Enterprise License",
  "Developer Sandbox",
  "Marketing Dashboard",
  "Analytics Suite",
  "Customer Portal",
  "Design System",
  "Mobile Prototype",
  "Beta Feature Access",
  "Team Collaboration",
  "Billing Profile",
  "Notification Center",
  "Security Settings",
  "Access Control",
  "Deployment Preview",
  "Production Server",
  "Task Scheduler",
  "Data Sync Job",
  "Error Monitor",
  "Performance Insights",
  "User Onboarding",
  "Audit Logs",
  "Storage Bucket",
  "Content Library",
  "API Gateway",
  "Backup Instance",
  "Search Index",
  "Test Environment",
  "Build Pipeline",
  "Usage Summary",
  "Email Campaign",
  "SEO Optimization",
  "Payment Method",
  "Invoice Record",
  "Support Ticket",
  "Integration Setup",
  "Webhook Endpoint",
  "OAuth App",
  "Developer Token",
  "Brand Assets",
  "Typography Kit",
  "Icon Pack",
  "Theme Preset",
  "Custom Domain",
  "DNS Zone",
  "SSL Certificate",
  "User Group",
  "Admin Console",
  "Feature Toggle",
  "Experiment Variant",
  "A/B Test Run",
  "Content Section",
  "Landing Page",
  "Product Catalog",
  "Inventory Item",
  "Discount Code",
  "Checkout Flow",
  "Shipping Option",
  "Order History",
  "Customer Profile",
  "Device Binding",
  "App Integration",
  "Widget Embed",
  "Media Upload",
  "Report Template",
  "Data Export",
  "Import Job",
  "Query Builder",
  "Saved Filter",
  "Heatmap View",
  "Session Replay",
  "Crash Report",
  "Notification Rule",
  "Email Template",
  "SMS Gateway",
  "Voice Channel",
  "AI Assistant",
  "Chat Transcript",
  "Automation Flow",
  "Schedule Trigger",
  "Team Role",
  "Workspace Member",
  "Archived Project",
  "Design Token",
  "Global Variable",
  "Localization Pack",
  "Feature Request",
  "Bug Report",
  "Release Note",
  "Changelog Entry",
  "License Key",
  "System Health",
  "Load Balancer",
  "Cache Layer",
  "Database Cluster",
  "Compute Node",
  "API Key",
  "Environment Variable",
  "Service Account",
  "Cloud Function",
  "Resource Policy"
]
const singleWordTitles = [
  "Aurora","Beacon","Catalyst","Nexus","Orbit","Pulse","Vertex","Echo","Zenith","Horizon",
  "Quantum","Fusion","Vector","Nimbus","Axis","Summit","Prism","Flux","Vertex","Halo",
  "Spectra","Nova","Lumen","Voyage","Drift","Lyric","Haven","Arc","Spire","Core",
  "Tide","Shift","Bridge","Anchor","Field","Forge","Trail","Sierra","Atlas","Mosaic",
  "Signal","Delta","Vertex","Origin","Nimbus","Circuit","Frame","Trace","Realm","Strata",
  "Phase","Scope","Studio","Motion","Vault","Beacon","Coda","Module","Aspect","Matrix",
  "Frontier","Vantage","Stream","Focus","Aspect","Halo","Peak","Cluster","Wave","Canvas",
  "Vector","Pulse","Origin","Nimbus","Apex","Portal","Cycle","Horizon","Frame","Axis",
  "Lumen","Summit","Glide","Crux","Drift","Field","Orbit","Vertex","Vault","Nexus",
  "Zenith","Prism","Scope","Arc","Trail","Spire","Signal","Echo","Shift","Core"
]
const multiWordTitles = [
  "Smart Energy Dashboard",
  "Cloud Data Pipeline",
  "User Feedback Portal",
  "Marketing Insights Hub",
  "Team Collaboration Suite",
  "AI Content Generator",
  "Secure Payment Gateway",
  "Customer Support Center",
  "Real Time Analytics",
  "Document Management System",
  "Remote Access Console",
  "Automated Backup Service",
  "Product Review Tracker",
  "Website Optimization Tool",
  "Content Delivery Network",
  "Visual Design Editor",
  "Dynamic Pricing Engine",
  "Voice Command Assistant",
  "Inventory Control Panel",
  "Interactive Training Module",
  "Workflow Automation Hub",
  "Cross Platform Integration",
  "Customer Engagement Dashboard",
  "Live Event Monitor",
  "Predictive Maintenance Tool",
  "Global Shipping Manager",
  "Cloud Resource Manager",
  "Advanced Report Builder",
  "Employee Scheduling System",
  "Smart Contract Manager",
  "Data Encryption Utility",
  "Project Tracking Dashboard",
  "Content Approval Workflow",
  "User Session Recorder",
  "Custom Notification Rules",
  "Adaptive Learning Platform",
  "Visual Heatmap Report",
  "Digital Signature Service",
  "AI Search Assistant",
  "Automated Invoicing Tool",
  "IoT Device Registry",
  "Machine Learning Model",
  "Media Conversion Studio",
  "Incident Response Center",
  "Marketing Campaign Builder",
  "Interactive Tutorial Builder",
  "Enterprise Resource Hub",
  "Mobile Data Sync",
  "Customer Insight Studio",
  "Traffic Optimization Dashboard",
  "Compliance Audit Manager",
  "Business Continuity Plan",
  "Website A/B Testing Tool",
  "Performance Alert System",
  "Data Migration Wizard",
  "User Access Manager",
  "Payment Reconciliation Tool",
  "Subscription Control Panel",
  "Customer Feedback Collector",
  "Data Visualization Studio",
  "SEO Keyword Analyzer",
  "Content Scheduling Board",
  "Remote System Monitor",
  "Smart Notification Center",
  "Voice Response Platform",
  "User Behavior Tracker",
  "Team Knowledge Base",
  "Digital Asset Vault",
  "Fleet Management System",
  "Meeting Summary Generator",
  "Workflow Builder Pro",
  "AI Translation Assistant",
  "Online Booking Portal",
  "Risk Assessment Dashboard",
  "Feature Rollout Manager",
  "Incident Tracking Board",
  "API Performance Monitor",
  "Product Comparison Table",
  "User Preference Center",
  "Test Automation Framework",
  "Continuous Deployment Tool",
  "Data Validation Utility",
  "Mobile Security Suite",
  "Customer Reward Manager",
  "Email Delivery Service",
  "Bug Tracking System",
  "Inventory Forecast Engine",
  "Interactive Data Explorer",
  "File Sharing Workspace",
  "Contract Approval System",
  "Employee Performance Tracker",
  "Error Reporting Console",
  "Smart Lighting Control",
  "Budget Planning Tool",
  "Cloud Storage Hub",
  "Document Collaboration Space",
  "Visual Workflow Designer",
  "App Usage Analytics",
  "Customer Retention Hub",
  "Server Health Dashboard",
  "Subscription Renewal Manager",
  "Team Task Organizer"
]

export const cardTitles = sampleTitles
  .concat(singleWordTitles)
  .concat(multiWordTitles)

export const cardDescriptions = [
  "Includes essential tools to get started quickly.",
  "Provides advanced metrics and priority support.",
  "Ideal for growing teams managing multiple clients.",
  "A safe testing environment for developers.",
  "Visualize campaign performance in real time.",
  "Comprehensive data analysis and visualization.",
  "Secure login portal for your customers.",
  "Unified component library for consistent UIs.",
  "Interactive mockup for early user testing.",
  "Gain early access to unreleased features.",
  "Enable team members to share and comment.",
  "Manage your payment preferences and invoices.",
  "Stay informed with alerts and announcements.",
  "Adjust password and authentication options.",
  "Fine-tune user roles and permissions.",
  "Preview deployment before going live.",
  "Monitor uptime and server utilization.",
  "Automatically execute recurring tasks.",
  "Synchronize external databases nightly.",
  "Receive alerts for application errors.",
  "Track app speed and loading times.",
  "Guide new users through setup steps.",
  "View system activity and access trails.",
  "Scalable storage for documents and media.",
  "Central hub for managing brand content.",
  "Route API traffic efficiently and securely.",
  "Keep redundant backups of your data.",
  "Optimize search results with filters.",
  "Create isolated test environments easily.",
  "Build and release your app automatically.",
  "Monitor resource usage and billing trends.",
  "Plan and send targeted marketing emails.",
  "Improve your search engine visibility.",
  "Add or update your preferred payment card.",
  "View or download past billing statements.",
  "Contact support or open a new case.",
  "Connect with external software tools.",
  "Receive data automatically via webhooks.",
  "Register third-party OAuth integrations.",
  "Manage tokens for developer access.",
  "Organize and share official brand files.",
  "Predefined font and spacing guidelines.",
  "Curated icon collection for interfaces.",
  "Apply a color and spacing preset instantly.",
  "Connect your website to a personal domain.",
  "Manage DNS records and subdomains.",
  "Generate and renew SSL certificates.",
  "Group users under common permissions.",
  "Administrative tools for system managers.",
  "Enable or disable experimental functions.",
  "Run controlled A/B experiments easily.",
  "Track performance across test variants.",
  "Create and manage structured content.",
  "Design and publish responsive pages.",
  "Manage products and categories online.",
  "Keep stock levels accurate automatically.",
  "Offer time-limited discounts to buyers.",
  "Streamline checkout for faster purchases.",
  "Choose regional or express delivery.",
  "Browse all previous transactions.",
  "Manage personal data and preferences.",
  "Link devices for easier access.",
  "Integrate with popular business apps.",
  "Embed widgets into third-party pages.",
  "Upload new images, videos, or files.",
  "Customize layout with reusable templates.",
  "Download reports in multiple formats.",
  "Import external data from spreadsheets.",
  "Build complex queries visually.",
  "Save custom filters for reuse.",
  "Visualize engagement via heatmaps.",
  "Replay user sessions for analysis.",
  "Identify app crashes and failure points.",
  "Create automated notification triggers.",
  "Design professional message templates.",
  "Configure text delivery for alerts.",
  "Connect voice services to customers.",
  "Automate responses with smart AI tools.",
  "Review chat history and summaries.",
  "Define steps in an automation workflow.",
  "Trigger actions based on time or events.",
  "Assign roles and adjust permissions.",
  "Invite or remove team members.",
  "Archive completed or old projects.",
  "Define tokens for color and spacing.",
  "Manage environment-level variables.",
  "Add translations for multiple locales.",
  "Submit new ideas to the roadmap.",
  "Report issues directly to developers.",
  "Summarize updates for the latest release.",
  "Record and publish recent changes.",
  "Store activation keys securely.",
  "Monitor overall system performance.",
  "Distribute load across multiple servers.",
  "Cache frequent data for faster access.",
  "Scale database capacity dynamically.",
  "Provision compute resources instantly.",
  "Generate and revoke API credentials.",
  "Manage secure configuration settings.",
  "Grant access for background services.",
  "Deploy lightweight cloud functions.",
  "Define usage rules and access policies."
]



