// util/faker/text.ts
import { randomPick } from '../random'

const SENTENCES = [
  'The quick brown fox jumps over the lazy dog.',
  'A watched pot never boils.',
  'She sells seashells by the seashore.',
  'Every cloud has a silver lining.',
  'Time waits for no one.',
  'The rain in Spain falls mainly on the plain.',
  'Better late than never.',
  'Actions speak louder than words.',
  'Curiosity killed the cat.',
  'Don’t count your chickens before they hatch.',
  'You can’t judge a book by its cover.',
  'Honesty is the best policy.',
  'A picture is worth a thousand words.',
  'Practice makes perfect.',
  'The early bird catches the worm.',
  'Beggars can’t be choosers.',
  'When in Rome, do as the Romans do.',
  'Two wrongs don’t make a right.',
  'A stitch in time saves nine.',
  'Birds of a feather flock together.',
  'Beauty is in the eye of the beholder.',
  'A penny saved is a penny earned.',
  'Fortune favors the bold.',
  'Out of sight, out of mind.',
  'Necessity is the mother of invention.',
  'The grass is always greener on the other side.',
  'Too many cooks spoil the broth.',
  'Don’t bite the hand that feeds you.',
  'All that glitters is not gold.',
  'You reap what you sow.',
  'Look before you leap.',
  'Jack of all trades, master of none.',
  'No pain, no gain.',
  'A journey of a thousand miles begins with a single step.',
  'The pen is mightier than the sword.',
  'Still waters run deep.',
  'Absence makes the heart grow fonder.',
  'Hope for the best, prepare for the worst.',
  'There’s no smoke without fire.',
  'Barking dogs seldom bite.',
  'Don’t put all your eggs in one basket.',
  'Old habits die hard.',
  'You can’t have your cake and eat it too.',
  'Good things come to those who wait.',
  'If it ain’t broke, don’t fix it.',
  'All good things must come to an end.',
  'It takes two to tango.',
  'Every dog has its day.',
  'Silence is golden.',
  'The squeaky wheel gets the grease.',
  'No man is an island.',
  'You can lead a horse to water, but you can’t make it drink.',
  'Knowledge is power.',
  'The apple doesn’t fall far from the tree.',
  'Rome wasn’t built in a day.',
  'Necessity knows no law.',
  'Don’t cry over spilled milk.',
  'A fool and his money are soon parted.',
  'Laughter is the best medicine.',
  'Blood is thicker than water.',
  'An apple a day keeps the doctor away.',
  'Where there’s a will, there’s a way.',
  'Easy come, easy go.',
  'Many hands make light work.',
  'You can’t please everyone.',
  'What goes around comes around.',
  'The road to hell is paved with good intentions.',
  'When the going gets tough, the tough get going.',
  'Don’t put off until tomorrow what you can do today.',
  'If you can’t beat them, join them.',
  'Variety is the spice of life.',
  'There’s no place like home.',
  'Necessity sharpens the wit.',
  'You win some, you lose some.',
  'Don’t make a mountain out of a molehill.',
  'Ignorance is bliss.',
  'Haste makes waste.',
  'Bite the bullet.',
  'Every rose has its thorn.',
  'A chain is only as strong as its weakest link.',
  'Familiarity breeds contempt.',
  'It’s better to be safe than sorry.',
  'You can’t teach an old dog new tricks.',
  'Don’t judge a man until you’ve walked a mile in his shoes.',
  'Appearances can be deceiving.',
  'Necessity breeds resourcefulness.',
  'Good fences make good neighbors.',
  'There’s no such thing as a free lunch.',
  'The proof is in the pudding.',
  'You can’t make an omelet without breaking eggs.',
  'The best things in life are free.',
  'What’s done is done.',
  'One man’s trash is another man’s treasure.',
  'A rolling stone gathers no moss.',
  'The customer is always right.',
  'The end justifies the means.',
  'To err is human; to forgive, divine.',
  'Don’t burn your bridges.',
  'Strike while the iron is hot.',
  'All’s fair in love and war.',
]

export function getRandomSentences(n: number): string {
  return Array.from({ length: n }, () => randomPick(SENTENCES)).join(' ')
}
